server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/desafio
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3sj8jv24
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect